### ISSUE TITLE
Would updating be possible?

### ISSUE THREAD

**Issue by KomiNeko** [JumpmanSr/BailOutMode#6]
I understand that you feel your objective was achieved and I can respect that given the change that Beat Saber had in follow up to your mod.

However, what the game currently seems to do is to remove the energy better and even though there's no score submission the level is still labelled as cleared at the end, while using BailOutMode made it so that some track of energy was maintained AND the level was correctly marked as failed. This method was useful to use in tandem with certain other mods.

I do not understand what is necessary to make the mod functional with the current version, but if you feel the alterations are simple, would it be possible to bring the mod up to date?

Many thanks in advance and thank you for maintaining this to where you did!

**Comment by JumpmanSr** [comment]
Hello, I decided to update it. It's very barebones in it's current state because I have not been keeping up with the modding community but the functionality is there. Unfortunately it won't be toggleable ingame (there is a settings option that can enable/disable it between launches), I may add that at a later time along with some QOL stuff. But I'll be pushing it live shortly here. Thank you for your continued interest. 

Ps. Sorry, I don't know why I don't get emails from these, I would've resolved this much faster. 
[BailOutMode - 1.16.2 .zip](https://github.com/JumpmanSr/BailOutMode/files/6757464/BailOutMode.-.1.16.2.zip)
